#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinTech101.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Argaam_Analytics")]
	public partial class ArgaamAnalyticsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGlobalEvent(GlobalEvent instance);
    partial void UpdateGlobalEvent(GlobalEvent instance);
    partial void DeleteGlobalEvent(GlobalEvent instance);
    #endregion
		
		public ArgaamAnalyticsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Argaam_AnalyticsConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ArgaamAnalyticsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ArgaamAnalyticsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ArgaamAnalyticsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ArgaamAnalyticsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Company> Companies
		{
			get
			{
				return this.GetTable<Company>();
			}
		}
		
		public System.Data.Linq.Table<GlobalEvent> GlobalEvents
		{
			get
			{
				return this.GetTable<GlobalEvent>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CommpanyGoodAndBadDays")]
		public ISingleResult<SP_CommpanyGoodAndBadDaysResult> SP_CommpanyGoodAndBadDays([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> company_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> year)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), company_id, year);
			return ((ISingleResult<SP_CommpanyGoodAndBadDaysResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_MonthsCompanyWasUpOrDown")]
		public ISingleResult<SP_MonthsCompanyWasUpOrDownResult> SP_MonthsCompanyWasUpOrDown([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> from_year, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> to_year, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> company_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), from_year, to_year, company_ID);
			return ((ISingleResult<SP_MonthsCompanyWasUpOrDownResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PricesAroundEvents")]
		public ISingleResult<SP_PricesAroundEventsResult> SP_PricesAroundEvents([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> p_event_date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_week_before, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_week_after, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_company_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_event_date, p_week_before, p_week_after, p_company_id);
			return ((ISingleResult<SP_PricesAroundEventsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_MonthsInWhichCompaniesWereUpAndDown")]
		public ISingleResult<SP_MonthsInWhichCompaniesWereUpAndDownResult> SP_MonthsInWhichCompaniesWereUpAndDown([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> from_year, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> to_year)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), from_year, to_year);
			return ((ISingleResult<SP_MonthsInWhichCompaniesWereUpAndDownResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CompanyUpOrDownByPercent")]
		public ISingleResult<SP_CompanyUpOrDownByPercentResult> SP_CompanyUpOrDownByPercent([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_company_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(8)")] string p_up_or_down, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> p_percent, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_from_year, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_to_year)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_company_id, p_up_or_down, p_percent, p_from_year, p_to_year);
			return ((ISingleResult<SP_CompanyUpOrDownByPercentResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Companies")]
	public partial class Company
	{
		
		private int _CompanyID;
		
		private string _CompanyNameEn;
		
		private string _CompanyNameAr;
		
		private bool _HasOnlyBasicProfile;
		
		private string _StockSymbol;
		
		private System.Nullable<short> _MarketStatusID;
		
		private System.Nullable<short> _OwnershipTypeID;
		
		private System.Nullable<short> _CompanyActivityCategoryID;
		
		private string _ShortNameEn;
		
		private string _ShortNameAr;
		
		private bool _IsActive;
		
		private System.Nullable<short> _CurrencyID;
		
		private System.Nullable<short> _CountryOfOriginID;
		
		private System.Nullable<int> _LogoID;
		
		private string _LogoURL;
		
		private System.Nullable<byte> _YearEndMonth;
		
		private System.Nullable<short> _ArgaamID;
		
		private System.Nullable<bool> _IsVisibleInPetrochemical;
		
		private System.Nullable<short> _SalaryUnit;
		
		private System.Nullable<short> _CountryID;
		
		private System.Nullable<short> _CityID;
		
		private bool _IsTotalSalariesAndBonusesUsed;
		
		private bool _IsBroker;
		
		private bool _IsSponsor;
		
		public Company()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="Int NOT NULL")]
		public int CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this._CompanyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyNameEn", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string CompanyNameEn
		{
			get
			{
				return this._CompanyNameEn;
			}
			set
			{
				if ((this._CompanyNameEn != value))
				{
					this._CompanyNameEn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyNameAr", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string CompanyNameAr
		{
			get
			{
				return this._CompanyNameAr;
			}
			set
			{
				if ((this._CompanyNameAr != value))
				{
					this._CompanyNameAr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasOnlyBasicProfile", DbType="Bit NOT NULL")]
		public bool HasOnlyBasicProfile
		{
			get
			{
				return this._HasOnlyBasicProfile;
			}
			set
			{
				if ((this._HasOnlyBasicProfile != value))
				{
					this._HasOnlyBasicProfile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockSymbol", DbType="VarChar(8)")]
		public string StockSymbol
		{
			get
			{
				return this._StockSymbol;
			}
			set
			{
				if ((this._StockSymbol != value))
				{
					this._StockSymbol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarketStatusID", DbType="SmallInt")]
		public System.Nullable<short> MarketStatusID
		{
			get
			{
				return this._MarketStatusID;
			}
			set
			{
				if ((this._MarketStatusID != value))
				{
					this._MarketStatusID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnershipTypeID", DbType="SmallInt")]
		public System.Nullable<short> OwnershipTypeID
		{
			get
			{
				return this._OwnershipTypeID;
			}
			set
			{
				if ((this._OwnershipTypeID != value))
				{
					this._OwnershipTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyActivityCategoryID", DbType="SmallInt")]
		public System.Nullable<short> CompanyActivityCategoryID
		{
			get
			{
				return this._CompanyActivityCategoryID;
			}
			set
			{
				if ((this._CompanyActivityCategoryID != value))
				{
					this._CompanyActivityCategoryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortNameEn", DbType="VarChar(64)")]
		public string ShortNameEn
		{
			get
			{
				return this._ShortNameEn;
			}
			set
			{
				if ((this._ShortNameEn != value))
				{
					this._ShortNameEn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortNameAr", DbType="NVarChar(64)")]
		public string ShortNameAr
		{
			get
			{
				return this._ShortNameAr;
			}
			set
			{
				if ((this._ShortNameAr != value))
				{
					this._ShortNameAr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrencyID", DbType="SmallInt")]
		public System.Nullable<short> CurrencyID
		{
			get
			{
				return this._CurrencyID;
			}
			set
			{
				if ((this._CurrencyID != value))
				{
					this._CurrencyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryOfOriginID", DbType="SmallInt")]
		public System.Nullable<short> CountryOfOriginID
		{
			get
			{
				return this._CountryOfOriginID;
			}
			set
			{
				if ((this._CountryOfOriginID != value))
				{
					this._CountryOfOriginID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogoID", DbType="Int")]
		public System.Nullable<int> LogoID
		{
			get
			{
				return this._LogoID;
			}
			set
			{
				if ((this._LogoID != value))
				{
					this._LogoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogoURL", DbType="NVarChar(1024)")]
		public string LogoURL
		{
			get
			{
				return this._LogoURL;
			}
			set
			{
				if ((this._LogoURL != value))
				{
					this._LogoURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearEndMonth", DbType="TinyInt")]
		public System.Nullable<byte> YearEndMonth
		{
			get
			{
				return this._YearEndMonth;
			}
			set
			{
				if ((this._YearEndMonth != value))
				{
					this._YearEndMonth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArgaamID", DbType="SmallInt")]
		public System.Nullable<short> ArgaamID
		{
			get
			{
				return this._ArgaamID;
			}
			set
			{
				if ((this._ArgaamID != value))
				{
					this._ArgaamID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsVisibleInPetrochemical", DbType="Bit")]
		public System.Nullable<bool> IsVisibleInPetrochemical
		{
			get
			{
				return this._IsVisibleInPetrochemical;
			}
			set
			{
				if ((this._IsVisibleInPetrochemical != value))
				{
					this._IsVisibleInPetrochemical = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalaryUnit", DbType="SmallInt")]
		public System.Nullable<short> SalaryUnit
		{
			get
			{
				return this._SalaryUnit;
			}
			set
			{
				if ((this._SalaryUnit != value))
				{
					this._SalaryUnit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryID", DbType="SmallInt")]
		public System.Nullable<short> CountryID
		{
			get
			{
				return this._CountryID;
			}
			set
			{
				if ((this._CountryID != value))
				{
					this._CountryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityID", DbType="SmallInt")]
		public System.Nullable<short> CityID
		{
			get
			{
				return this._CityID;
			}
			set
			{
				if ((this._CityID != value))
				{
					this._CityID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsTotalSalariesAndBonusesUsed", DbType="Bit NOT NULL")]
		public bool IsTotalSalariesAndBonusesUsed
		{
			get
			{
				return this._IsTotalSalariesAndBonusesUsed;
			}
			set
			{
				if ((this._IsTotalSalariesAndBonusesUsed != value))
				{
					this._IsTotalSalariesAndBonusesUsed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBroker", DbType="Bit NOT NULL")]
		public bool IsBroker
		{
			get
			{
				return this._IsBroker;
			}
			set
			{
				if ((this._IsBroker != value))
				{
					this._IsBroker = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSponsor", DbType="Bit NOT NULL")]
		public bool IsSponsor
		{
			get
			{
				return this._IsSponsor;
			}
			set
			{
				if ((this._IsSponsor != value))
				{
					this._IsSponsor = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GlobalEvents")]
	public partial class GlobalEvent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GlobalEventID;
		
		private string _EventDesc;
		
		private System.DateTime _OccuredOn;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGlobalEventIDChanging(int value);
    partial void OnGlobalEventIDChanged();
    partial void OnEventDescChanging(string value);
    partial void OnEventDescChanged();
    partial void OnOccuredOnChanging(System.DateTime value);
    partial void OnOccuredOnChanged();
    #endregion
		
		public GlobalEvent()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GlobalEventID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int GlobalEventID
		{
			get
			{
				return this._GlobalEventID;
			}
			set
			{
				if ((this._GlobalEventID != value))
				{
					this.OnGlobalEventIDChanging(value);
					this.SendPropertyChanging();
					this._GlobalEventID = value;
					this.SendPropertyChanged("GlobalEventID");
					this.OnGlobalEventIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventDesc", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string EventDesc
		{
			get
			{
				return this._EventDesc;
			}
			set
			{
				if ((this._EventDesc != value))
				{
					this.OnEventDescChanging(value);
					this.SendPropertyChanging();
					this._EventDesc = value;
					this.SendPropertyChanged("EventDesc");
					this.OnEventDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OccuredOn", DbType="Date NOT NULL")]
		public System.DateTime OccuredOn
		{
			get
			{
				return this._OccuredOn;
			}
			set
			{
				if ((this._OccuredOn != value))
				{
					this.OnOccuredOnChanging(value);
					this.SendPropertyChanging();
					this._OccuredOn = value;
					this.SendPropertyChanged("OccuredOn");
					this.OnOccuredOnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class SP_CommpanyGoodAndBadDaysResult
	{
		
		private System.Nullable<int> _Day;
		
		private System.Nullable<int> _NoChange;
		
		private System.Nullable<int> _Positive;
		
		private System.Nullable<int> _Negative;
		
		public SP_CommpanyGoodAndBadDaysResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Day", DbType="Int")]
		public System.Nullable<int> Day
		{
			get
			{
				return this._Day;
			}
			set
			{
				if ((this._Day != value))
				{
					this._Day = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoChange", DbType="Int")]
		public System.Nullable<int> NoChange
		{
			get
			{
				return this._NoChange;
			}
			set
			{
				if ((this._NoChange != value))
				{
					this._NoChange = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Positive", DbType="Int")]
		public System.Nullable<int> Positive
		{
			get
			{
				return this._Positive;
			}
			set
			{
				if ((this._Positive != value))
				{
					this._Positive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Negative", DbType="Int")]
		public System.Nullable<int> Negative
		{
			get
			{
				return this._Negative;
			}
			set
			{
				if ((this._Negative != value))
				{
					this._Negative = value;
				}
			}
		}
	}
	
	public partial class SP_MonthsCompanyWasUpOrDownResult
	{
		
		private System.Nullable<int> _Year;
		
		private System.Nullable<decimal> @__1;
		
		private System.Nullable<decimal> @__2;
		
		private System.Nullable<decimal> @__3;
		
		private System.Nullable<decimal> @__4;
		
		private System.Nullable<decimal> @__5;
		
		private System.Nullable<decimal> @__6;
		
		private System.Nullable<decimal> @__7;
		
		private System.Nullable<decimal> @__8;
		
		private System.Nullable<decimal> @__9;
		
		private System.Nullable<decimal> @__10;
		
		private System.Nullable<decimal> @__11;
		
		private System.Nullable<decimal> @__12;
		
		public SP_MonthsCompanyWasUpOrDownResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="Int")]
		public System.Nullable<int> Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this._Year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1]", Storage="__1", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _1
		{
			get
			{
				return this.@__1;
			}
			set
			{
				if ((this.@__1 != value))
				{
					this.@__1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[2]", Storage="__2", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _2
		{
			get
			{
				return this.@__2;
			}
			set
			{
				if ((this.@__2 != value))
				{
					this.@__2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[3]", Storage="__3", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _3
		{
			get
			{
				return this.@__3;
			}
			set
			{
				if ((this.@__3 != value))
				{
					this.@__3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[4]", Storage="__4", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _4
		{
			get
			{
				return this.@__4;
			}
			set
			{
				if ((this.@__4 != value))
				{
					this.@__4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[5]", Storage="__5", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _5
		{
			get
			{
				return this.@__5;
			}
			set
			{
				if ((this.@__5 != value))
				{
					this.@__5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[6]", Storage="__6", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _6
		{
			get
			{
				return this.@__6;
			}
			set
			{
				if ((this.@__6 != value))
				{
					this.@__6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[7]", Storage="__7", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _7
		{
			get
			{
				return this.@__7;
			}
			set
			{
				if ((this.@__7 != value))
				{
					this.@__7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[8]", Storage="__8", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _8
		{
			get
			{
				return this.@__8;
			}
			set
			{
				if ((this.@__8 != value))
				{
					this.@__8 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[9]", Storage="__9", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _9
		{
			get
			{
				return this.@__9;
			}
			set
			{
				if ((this.@__9 != value))
				{
					this.@__9 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[10]", Storage="__10", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _10
		{
			get
			{
				return this.@__10;
			}
			set
			{
				if ((this.@__10 != value))
				{
					this.@__10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[11]", Storage="__11", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _11
		{
			get
			{
				return this.@__11;
			}
			set
			{
				if ((this.@__11 != value))
				{
					this.@__11 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[12]", Storage="__12", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _12
		{
			get
			{
				return this.@__12;
			}
			set
			{
				if ((this.@__12 != value))
				{
					this.@__12 = value;
				}
			}
		}
	}
	
	public partial class SP_PricesAroundEventsResult
	{
		
		private System.Nullable<System.DateTime> _ForDate;
		
		private string _DoW;
		
		private System.Nullable<int> _CID;
		
		private System.Nullable<decimal> _Close;
		
		public SP_PricesAroundEventsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ForDate", DbType="Date")]
		public System.Nullable<System.DateTime> ForDate
		{
			get
			{
				return this._ForDate;
			}
			set
			{
				if ((this._ForDate != value))
				{
					this._ForDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoW", DbType="NVarChar(30)")]
		public string DoW
		{
			get
			{
				return this._DoW;
			}
			set
			{
				if ((this._DoW != value))
				{
					this._DoW = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CID", DbType="Int")]
		public System.Nullable<int> CID
		{
			get
			{
				return this._CID;
			}
			set
			{
				if ((this._CID != value))
				{
					this._CID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Close]", Storage="_Close", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Close
		{
			get
			{
				return this._Close;
			}
			set
			{
				if ((this._Close != value))
				{
					this._Close = value;
				}
			}
		}
	}
	
	public partial class SP_MonthsInWhichCompaniesWereUpAndDownResult
	{
		
		private int _CompanyID;
		
		private System.Nullable<int> _Year;
		
		private System.Nullable<decimal> @__1;
		
		private System.Nullable<decimal> @__2;
		
		private System.Nullable<decimal> @__3;
		
		private System.Nullable<decimal> @__4;
		
		private System.Nullable<decimal> @__5;
		
		private System.Nullable<decimal> @__6;
		
		private System.Nullable<decimal> @__7;
		
		private System.Nullable<decimal> @__8;
		
		private System.Nullable<decimal> @__9;
		
		private System.Nullable<decimal> @__10;
		
		private System.Nullable<decimal> @__11;
		
		private System.Nullable<decimal> @__12;
		
		public SP_MonthsInWhichCompaniesWereUpAndDownResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="Int NOT NULL")]
		public int CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this._CompanyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="Int")]
		public System.Nullable<int> Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this._Year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1]", Storage="__1", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _1
		{
			get
			{
				return this.@__1;
			}
			set
			{
				if ((this.@__1 != value))
				{
					this.@__1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[2]", Storage="__2", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _2
		{
			get
			{
				return this.@__2;
			}
			set
			{
				if ((this.@__2 != value))
				{
					this.@__2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[3]", Storage="__3", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _3
		{
			get
			{
				return this.@__3;
			}
			set
			{
				if ((this.@__3 != value))
				{
					this.@__3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[4]", Storage="__4", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _4
		{
			get
			{
				return this.@__4;
			}
			set
			{
				if ((this.@__4 != value))
				{
					this.@__4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[5]", Storage="__5", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _5
		{
			get
			{
				return this.@__5;
			}
			set
			{
				if ((this.@__5 != value))
				{
					this.@__5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[6]", Storage="__6", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _6
		{
			get
			{
				return this.@__6;
			}
			set
			{
				if ((this.@__6 != value))
				{
					this.@__6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[7]", Storage="__7", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _7
		{
			get
			{
				return this.@__7;
			}
			set
			{
				if ((this.@__7 != value))
				{
					this.@__7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[8]", Storage="__8", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _8
		{
			get
			{
				return this.@__8;
			}
			set
			{
				if ((this.@__8 != value))
				{
					this.@__8 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[9]", Storage="__9", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _9
		{
			get
			{
				return this.@__9;
			}
			set
			{
				if ((this.@__9 != value))
				{
					this.@__9 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[10]", Storage="__10", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _10
		{
			get
			{
				return this.@__10;
			}
			set
			{
				if ((this.@__10 != value))
				{
					this.@__10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[11]", Storage="__11", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _11
		{
			get
			{
				return this.@__11;
			}
			set
			{
				if ((this.@__11 != value))
				{
					this.@__11 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[12]", Storage="__12", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _12
		{
			get
			{
				return this.@__12;
			}
			set
			{
				if ((this.@__12 != value))
				{
					this.@__12 = value;
				}
			}
		}
	}
	
	public partial class SP_CompanyUpOrDownByPercentResult
	{
		
		private System.Nullable<int> _year;
		
		private System.Nullable<int> _month;
		
		private System.Nullable<int> _day;
		
		private string _theDate;
		
		public SP_CompanyUpOrDownByPercentResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year", DbType="Int")]
		public System.Nullable<int> year
		{
			get
			{
				return this._year;
			}
			set
			{
				if ((this._year != value))
				{
					this._year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_month", DbType="Int")]
		public System.Nullable<int> month
		{
			get
			{
				return this._month;
			}
			set
			{
				if ((this._month != value))
				{
					this._month = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_day", DbType="Int")]
		public System.Nullable<int> day
		{
			get
			{
				return this._day;
			}
			set
			{
				if ((this._day != value))
				{
					this._day = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_theDate", DbType="NVarChar(33)")]
		public string theDate
		{
			get
			{
				return this._theDate;
			}
			set
			{
				if ((this._theDate != value))
				{
					this._theDate = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
