<?xml version="1.0" encoding="utf-8"?><Database Name="Argaam_Analytics" Class="ArgaamAnalyticsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=172.16.3.51;Initial Catalog=Argaam_Analytics;User ID=argplus_user" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Argaam_AnalyticsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Companies" Member="Companies">
    <Type Name="Company">
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CompanyNameEn" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyNameAr" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="HasOnlyBasicProfile" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="StockSymbol" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="MarketStatusID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="OwnershipTypeID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CompanyActivityCategoryID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ShortNameEn" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="ShortNameAr" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CurrencyID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CountryOfOriginID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="LogoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LogoURL" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="YearEndMonth" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="ArgaamID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="IsVisibleInPetrochemical" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SalaryUnit" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CountryID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CityID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="IsTotalSalariesAndBonusesUsed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsBroker" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsSponsor" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.GlobalEvents" Member="GlobalEvents">
    <Type Name="GlobalEvent">
      <Column Name="GlobalEventID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EventDesc" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="OccuredOn" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.SP_CommpanyGoodAndBadDays" Method="SP_CommpanyGoodAndBadDays">
    <Parameter Name="company_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="year" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_CommpanyGoodAndBadDaysResult">
      <Column Name="Day" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoChange" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Positive" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Negative" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_CompanyUpOrDownByPercent" Method="SP_CompanyUpOrDownByPercent">
    <Parameter Name="p_company_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_up_or_down" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="p_percent" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="p_year" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_CompanyUpOrDownByPercentResult">
      <Column Name="ForDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_MonthsCompanyWasUpOrDown" Method="SP_MonthsCompanyWasUpOrDown">
    <Parameter Name="from_year" Type="System.Int32" DbType="Int" />
    <Parameter Name="to_year" Type="System.Int32" DbType="Int" />
    <Parameter Name="company_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_MonthsCompanyWasUpOrDownResult">
      <Column Name="Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[1]" Member="_1" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[2]" Member="_2" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[3]" Member="_3" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[4]" Member="_4" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[5]" Member="_5" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[6]" Member="_6" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[7]" Member="_7" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[8]" Member="_8" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[9]" Member="_9" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[10]" Member="_10" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[11]" Member="_11" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[12]" Member="_12" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_PricesAroundEvents" Method="SP_PricesAroundEvents">
    <Parameter Name="p_event_date" Type="System.DateTime" DbType="Date" />
    <Parameter Name="p_week_before" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_week_after" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_company_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_PricesAroundEventsResult">
      <Column Name="ForDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DoW" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="CID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_MonthsInWhichCompaniesWereUpAndDown" Method="SP_MonthsInWhichCompaniesWereUpAndDown">
    <Parameter Name="from_year" Type="System.Int32" DbType="Int" />
    <Parameter Name="to_year" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_MonthsInWhichCompaniesWereUpAndDownResult">
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[1]" Member="_1" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[2]" Member="_2" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[3]" Member="_3" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[4]" Member="_4" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[5]" Member="_5" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[6]" Member="_6" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[7]" Member="_7" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[8]" Member="_8" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[9]" Member="_9" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[10]" Member="_10" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[11]" Member="_11" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[12]" Member="_12" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>