<?xml version="1.0" encoding="utf-8"?><Database Name="Argaam_Analytics" Class="ArgaamAnalyticsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=172.16.3.51;Initial Catalog=Argaam_Analytics;User ID=argplus_user" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Argaam_AnalyticsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.GlobalEventCategories" Member="GlobalEventCategories">
    <Type Name="GlobalEventCategory">
      <Column Name="EventCategoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EventCategoryName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.GlobalEvents" Member="GlobalEvents">
    <Type Name="GlobalEvent">
      <Column Name="GlobalEventID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EventCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="EventDesc" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="StartsOn" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="EndsOn" Type="System.DateTime" DbType="Date" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.StockEntities" Member="StockEntities">
    <Type Name="StockEntity">
      <Column Name="StockEntityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StockEntityTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NameEn" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="NameAr" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="ShortNameEn" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ShortNameAr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Symbol" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.StockEntityTypes" Member="StockEntityTypes">
    <Type Name="StockEntityType">
      <Column Name="StockEntityTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StockEntityTypeName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.StockEntityPrices" Member="StockEntityPrices">
    <Type Name="StockEntityPrice">
      <Column Name="StockEntityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StockEntityTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ForDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="[Open]" Member="Open" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="[Close]" Member="Close" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Min" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Max" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Volume" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Amount" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.SP_Q1_StockEntityWasUpOrDownByPercent" Method="SP_Q1_StockEntityWasUpOrDownByPercent">
    <Parameter Name="p_stock_entity_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_stock_entity_type_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_up_or_down" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="p_percent" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="p_from_year" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_to_year" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_Q1_StockEntityWasUpOrDownByPercentResult">
      <Column Name="year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="month" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="day" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="theDate" Type="System.String" DbType="NVarChar(33)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_Q2_StockEntityGoodAndBadDays" Method="SP_Q2_StockEntityGoodAndBadDays">
    <Parameter Name="p_se_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_se_type_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_year" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_Q2_StockEntityGoodAndBadDaysResult">
      <Column Name="Day" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoChange" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Positive" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Negative" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_Q3_StockEntityUpDownMonths" Method="SP_Q3_StockEntityUpDownMonths">
    <Parameter Name="p_from_year" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_to_year" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_se_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_se_type_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_Q3_StockEntityUpDownMonthsResult">
      <Column Name="Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[1]" Member="_1" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[2]" Member="_2" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[3]" Member="_3" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[4]" Member="_4" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[5]" Member="_5" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[6]" Member="_6" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[7]" Member="_7" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[8]" Member="_8" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[9]" Member="_9" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[10]" Member="_10" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[11]" Member="_11" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[12]" Member="_12" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_Q5_StockEntityTypeUpAndDownMonths" Method="SP_Q5_StockEntityTypeUpAndDownMonths">
    <Parameter Name="p_from_year" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_to_year" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_se_type_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_Q5_StockEntityTypeUpAndDownMonthsResult">
      <Column Name="StockEntityTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StockEntityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[1]" Member="_1" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[2]" Member="_2" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[3]" Member="_3" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[4]" Member="_4" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[5]" Member="_5" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[6]" Member="_6" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[7]" Member="_7" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[8]" Member="_8" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[9]" Member="_9" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[10]" Member="_10" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[11]" Member="_11" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[12]" Member="_12" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_Q4_PricesAroundEventDate" Method="SP_Q4_PricesAroundEventDate">
    <Parameter Name="p_event_date" Type="System.DateTime" DbType="Date" />
    <Parameter Name="p_event_end_date" Type="System.DateTime" DbType="Date" />
    <Parameter Name="p_week_before" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_week_after" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_se_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_se_type_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_Q4_PricesAroundEventDateResult">
      <Column Name="ForDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DoW" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="seID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="setID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Close]" Member="Close" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>